/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pnwadexasppvtfxsllat"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBud2FkZXhhc3BwdnRmeHNsbGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MTYwNzMsImV4cCI6MjA3ODk5MjA3M30.LzcVAr-xUsQfE38B2bLb_7Np-mIMrLg9n_O8UCKtGfA"